development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: user1
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: user1
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: user1
  password:
  host: localhost

